-- 000_schema.sql
--
-- Creates the candidates table from scratch. Mirrors the live Supabase schema
-- (verified against information_schema on 2026-08-19) so that a local test
-- database exercises the same column types and constraints as production.
--
-- Only used to bootstrap a throwaway test database. Production already has
-- this table; do not run it there.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS candidates (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             varchar,
    raw_title        varchar,
    experience_years integer,
    phone            varchar,
    email            varchar UNIQUE,
    skills           text[],
    source_file      varchar,
    embedding        vector(384),
    created_at       timestamptz DEFAULT now()
);
